gdb: Refactor arcv2/arcv3 XML files
1. The following groups are introduced:

common:    mostly gpr registers
build:     build config registers
timer:     timer related
irq:       irq related
mmu:       mmu registers
mpu:       mpu registers
exception: exception related registers

one can print them using:

(gdb) i r mmu
(gdb) i r common
 ...

2. Moreover, the "regnum=xx" field is removed and only kept for
the first and last entry of each XML file.  This way it is easier
to move around registers in the same file, since it will be
calculated automatically. Still, adding a new register will have
an affect on the last "regnum=" and the first one of next XML file
if any.

3. Last but not least, arc-v{2,3_64}-other.xml files are merged
into their "arc-*-aux.xml" counterpart.