TCG Test for multiarch (DO NOT UPSTREAM)
When compiling the tcg test (make build-tcg), the multiarch tests present a
compilation error relates to undeclared 'FE_TONEAREST' enumeration value.
This enum need to be defined in 'fenv.h' newlibc header file for arc and arc64.

tcg tests for multiarch:

float_convs.c:26:7: error: 'FE_TONEAREST' undeclared here (not in a function)
   26 |     { FE_TONEAREST, "to nearest" },